blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'


urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    #path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    
]

hub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)

class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'


    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.
    tags = TaggableManager()


    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]


    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.publish.year, 
                                                 self.publish.month, 
                                                 self.publish.day, 
                                                 self.slug])
    


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)


    class Meta:
        ordering = ['created']
        indexes = [models.Index(fields=['created']),]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'
    

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render
from .models import Post, Comment
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.postgres.search import TrigramSimilarity
from django.core.mail import send_mail
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from .forms import EmailPostForm, CommentForm, SearchForm
from django.views.decorators.http import require_POST
from taggit.models import Tag, TaggedItem



def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.annotate(
                similarity=TrigramSimilarity('title', query),
            ).filter(similarity__gt=0.1).order_by('-similarity')

    return render(request, 'blog/post/search.html', {'form': form, 'query': query, 'results': results})

@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    # A comment was posted
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Create a comment object without saving it to the database
        comment = form.save(commit=False)
        # Assign the post to the comment
        comment.post = post
        # Save the comment to the database
        comment.save()
    return render(request, 'blog/post/comment.html', {'post': post, 'form': form, 'comment': comment})


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " f"{post.title}"
            message = f"Read{post.title} at {post_url}\n\n" f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'chiagoziemleonard@gmail.com', [cd['to']])
            sent = True
        else:
            form = EmailPostForm()
        return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})



def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            # .... send email
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form})


def post_list(request, tag_slug=None):
    posts = Post.published.all()
    tag = None

    if tag_slug:
        # Get the tag object or return 404 if not found
        tag = get_object_or_404(Tag, slug=tag_slug) 
        # Filter published posts to include only those with the specified tag
        posts = Post.published.filter(pk__in=TaggedItem.objects.filter(tag=tag).values_list('object_id', flat=True))
        
    # Pagination with 3 posts per page
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        # If page_number is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page_number is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)


    return render(request, 'blog/post/list.html', {'posts': posts, 'tag': tag})


def post_detail(request, id):
    try:
        post = Post.published.get(id=id)
    except Post.DoesNotExist:
        raise Http404("No Post found.")
    
    return render(request, 'blog/post/detail.html', {'post': post})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED, slug=post, publish__year=year, publish__month=month, publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    # Form for users to comment
    form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    
    return render(request, 'blog/post/detail.html', 
                  {'post': post, 
                   'comments': comments, 
                   'form': form, 
                   'similar_posts': similar_posts
                   })

blog/templates/blog/post/includes/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url "blog:post_comment" post.id %}" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
</form>


<div class="blog_d3 mt-4 shadow_box p-4 rounded_30">
    <h4 class="center_sm">Post Comment</h4>
    <hr class="line mb-4">
        <div class="blog_1dt2i row mt-3">
            <div class="col-md-12">
                <div class="blog_1dt2il">
                    <textarea placeholder="Message" class="form-control form_text"></textarea>
                </div>
            </div> 
        </div>
        <div class="blog_1dt2i row mt-4">
            <div class="col-md-6">
                <div class="blog_1dt2il">
                    <input class="form-control" placeholder="Name" type="text">
                </div>
            </div> 
            <div class="col-md-6">
                <div class="blog_1dt2il">
                    <input class="form-control" placeholder="Email" type="text">
                </div>
            </div>
        </div>
        <div class="blog_1dt2i row mt-4">
            <div class="col-md-6">
                <div class="blog_1dt2il">
                    <input class="form-control" placeholder="Subject" type="text">
                </div>
            </div> 
            <div class="col-md-6">
                <div class="blog_1dt2il">
                    <input class="form-control" placeholder="Website" type="text">
                </div>
            </div>
        </div>
        <div class="blog_1dt2i row mt-4">
            <div class="col-md-12">
                <div class="blog_1dt2il">
                    <h6 class="mb-0 center_sm"><a class="button" href="#">Submit Now</a></h6>
                </div>
            </div> 
        </div>
    </div>

blog/templates/blog/post/includes/footer.html
<section id="footer" class="px_4 p_3 bg-white">
    <div class="container-fluid">
    <div class="row footer_1">
        <div class="col">
            <div class="footer_1l">
                <h3 class="mb-4"><a  href="index.html"><i class="fa fa-blog text-primary col_blue"></i> Blogging</a></h3>
                <div class="row footer_3ism">
                    <h6 class="col-md-12 col-6"><i class="fa-brands fa-facebook  me-1"></i> <a  href="#"> Facebook</a></h6>
                    <h6 class="col-md-12 col-6 mt-2"><i class="fa-brands fa-twitter  me-1"></i> <a  href="#"> Twitter</a></h6>
                    <h6 class="col-md-12 col-6 mt-2"><i class="fa-brands fa-linkedin  me-1"></i> <a  href="#"> Linkedin</a></h6>
                    <h6 class="col-md-12 col-6 mt-2 mb-0"><i class="fa-brands fa-instagram  me-1"></i> <a  href="#"> Instagram</a></h6>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="footer_1l">
                <h5 class="mb-4 mt-2">Getting Started</h5>
                <div class="row footer_3ism">
                    <h6 class="col-md-12 col-6"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a  href="#"> About Us</a></h6>
                    <h6 class="col-md-12 col-6 mt-2"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a  href="#"> Installation</a></h6>
                    <h6 class="col-md-12 col-6 mt-2"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a  href="#"> Release Notes</a></h6>
                    <h6 class="col-md-12 col-6 mt-2"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a  href="#"> Upgrade Guide</a></h6>
                    <h6 class="col-md-12 col-6 mt-2"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a  href="#"> Browser Support</a></h6>
                    <h6 class="col-md-12 col-6 mt-2 mb-0"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a href="#"> Editor Support</a></h6>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="footer_1l">
                <h5 class="mb-4 mt-2">Explore</h5>
                <div class="row footer_3ism">
                    <h6 class="col-md-12 col-6"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a  href="#"> Design features</a></h6>
                    <h6 class="col-md-12 col-6 mt-2"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a  href="#"> Prototyping</a></h6>
                    <h6 class="col-md-12 col-6 mt-2"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a  href="#"> Design Systems</a></h6>
                    <h6 class="col-md-12 col-6 mt-2"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a  href="#"> Pricing</a></h6>
                    <h6 class="col-md-12 col-6 mt-2"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a  href="#"> Customers</a></h6>
                    <h6 class="col-md-12 col-6 mt-2 mb-0"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a href="#"> Know More</a></h6>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="footer_1l">
                <h5 class="mb-4 mt-2">Resources</h5>
                <div class="row footer_3ism">
                    <h6 class="col-md-12 col-6"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a  href="#">What's new </a></h6>
                    <h6 class="col-md-12 col-6 mt-2"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a  href="#"> Best practices</a></h6>
                    <h6 class="col-md-12 col-6 mt-2"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a  href="#"> Our Services</a></h6>
                    <h6 class="col-md-12 col-6 mt-2"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a  href="#"> Support</a></h6>
                    <h6 class="col-md-12 col-6 mt-2"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a  href="#"> What's new</a></h6>
                    <h6 class="col-md-12 col-6 mt-2 mb-0"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a href="#">Developers</a></h6>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="footer_1l">
                <h5 class="mb-4 mt-2">Community</h5>
                <div class="row footer_3ism">
                    <h6 class="col-md-12 col-6"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a  href="#">Discussion Forums</a></h6>
                    <h6 class="col-md-12 col-6 mt-2"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a  href="#"> Code of Conduct</a></h6>
                    <h6 class="col-md-12 col-6 mt-2"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a  href="#"> Community Resources</a></h6>
                    <h6 class="col-md-12 col-6 mt-2"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a  href="#"> Contributing</a></h6>
                    <h6 class="col-md-12 col-6 mt-2"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a  href="#"> Concurrent Mode</a></h6>
                    <h6 class="col-md-12 col-6 mt-2 mb-0"><i class="fa fa-circle col_blue me-1 font_6 align-middle"></i> <a href="#">Our Policy</a></h6>
                </div>
            </div>
        </div>
    </div>

    {% comment %}  {% endcomment %}
    <div class="row footer_2">
        <div class="col-md-8">
            <div class="footer_2l">
                <p class="mb-0">© 2024 Pharosfleet Limited. All Rights Reserved </p>
            </div>
        </div>
        <div class="col-md-4">
                <div class="footer_2r text-end">
                    <ul class="mb-0 font_15">
                        <li class="d-inline-block"><a href="#">Privacy Policy</a></li>
                        <li class="d-inline-block ms-2"><i class="fa fa-circle col_blue me-1 font_8 align-middle"></i> <a  href="#">Terms & Condition</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

blog/templates/blog/post/includes/nav.html
<section id="header">
    <nav class="navbar navbar-expand-md navbar-light  p-0 bg-white px_4" id="navbar_sticky">
      <div class="container-fluid">
        <a class="text-black p-0 navbar-brand fw-bold  lh-1" href="{% url 'blog:post_list' %}"><i class="fa fa-blog text-primary col_blue"></i> PharosFleet Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
           <ul class="navbar-nav mb-0 ms-auto">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'index' %}">Home</a>
            </li>
             
            <li class="nav-item">
              <a class="nav-link" href="#">About </a>
            </li>
            
            <li class="nav-item">
              <a class="nav-link border-end-0" href="#">Contact </a>
            </li>
    
          </ul>
          <ul class="navbar-nav mb-0 ms-auto">
              <li class="nav-item dropdown">
                    <a class="dropdown-toggle nav_hide nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      <i class="fa fa-search"></i>
                    </a>
                    <ul class="dropdown-menu drop_1 drop_search p-3" aria-labelledby="navbarDropdown" style="">
                      <form class="navbar-form" role="search">
                        <div class="input-group">
                            <input type="text" class="form-control font_14" placeholder="Search Keyword">
                            <span class="input-group-btn">
                                <button class="btn btn-primary bg_blue border-0 rounded-0 p-2 px-3" type="button">
                                    <i class="fa fa-search"></i> </button>
                            </span>
                        </div>
                      </form>
                    </ul>
              </li>
          </ul>
        </div>
      </div>
    </nav>
    </section>