blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'


urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    #path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    
]

hub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)

class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'


    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.
    tags = TaggableManager()


    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]


    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.publish.year, 
                                                 self.publish.month, 
                                                 self.publish.day, 
                                                 self.slug])
    


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)


    class Meta:
        ordering = ['created']
        indexes = [models.Index(fields=['created']),]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'
    

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render
from .models import Post, Comment
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.postgres.search import TrigramSimilarity
from django.core.mail import send_mail
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from .forms import EmailPostForm, CommentForm, SearchForm
from django.views.decorators.http import require_POST
from taggit.models import Tag, TaggedItem



def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.annotate(
                similarity=TrigramSimilarity('title', query),
            ).filter(similarity__gt=0.1).order_by('-similarity')

    return render(request, 'blog/post/search.html', {'form': form, 'query': query, 'results': results})

@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    # A comment was posted
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Create a comment object without saving it to the database
        comment = form.save(commit=False)
        # Assign the post to the comment
        comment.post = post
        # Save the comment to the database
        comment.save()
    return render(request, 'blog/post/comment.html', {'post': post, 'form': form, 'comment': comment})


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " f"{post.title}"
            message = f"Read{post.title} at {post_url}\n\n" f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'chiagoziemleonard@gmail.com', [cd['to']])
            sent = True
        else:
            form = EmailPostForm()
        return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})



def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            # .... send email
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form})


def post_list(request, tag_slug=None):
    posts = Post.published.all()
    tag = None

    if tag_slug:
        # Get the tag object or return 404 if not found
        tag = get_object_or_404(Tag, slug=tag_slug) 
        # Filter published posts to include only those with the specified tag
        posts = Post.published.filter(pk__in=TaggedItem.objects.filter(tag=tag).values_list('object_id', flat=True))
        
    # Pagination with 3 posts per page
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        # If page_number is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page_number is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)


    return render(request, 'blog/post/list.html', {'posts': posts, 'tag': tag})


def post_detail(request, id):
    try:
        post = Post.published.get(id=id)
    except Post.DoesNotExist:
        raise Http404("No Post found.")
    
    return render(request, 'blog/post/detail.html', {'post': post})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED, slug=post, publish__year=year, publish__month=month, publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    # Form for users to comment
    form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    
    return render(request, 'blog/post/detail.html', 
                  {'post': post, 
                   'comments': comments, 
                   'form': form, 
                   'similar_posts': similar_posts
                   })

blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}Add a comment{% endblock  %}

{% block content %}
{% if comment %}
    <h2>Your comment has been added.</h2>
    <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
{% else %}
    {% include "blog/post/includes/comment_form.html" %}
{% endif %}

{% endblock  %}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock  %}

{% block content %}

    {% comment %} <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url "blog:post_share" post.id %}">
            Share this post
        </a>
    </p>

    <h2>Similar posts</h2>
    {% for post in Similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created}}
            </p>
            {{ comment.body|linebreaks }}
        </div>
        {% empty %}
        <p>There are no comments.</p>
    {% endfor %}
        {% include "blog/post/includes/comment_form.html" %} {% endcomment %}




<section id="center" class="center_blogdt pt-5 pb-5 px_4">
    <div class="container-fluid">
        <div class="blog_pg1 row">
            <div class="col-md-8">
                <div class="blog_1dt">
                    <div class="blog_1dt1 shadow_box p-4 rounded_30">
                        <h3 class="mt-4 mb-3">{{ post.title }}</h3>
                        <div class="blog_1im2">
                            <ul class="mb-0">
                                <li class="d-inline-block">
                                    <a href="#">
                                        Published {{ post.publish }} by {{ post.author }}
                                    </a>
                                </li>
                            </ul>
                        </div><hr/>
                        <p>
                            {{ post.body|markdown }}
                        </p>
                       
                        <hr>
                        <h4 class="mb-3 mt-3 center_sm">
                            <a href="{% url "blog:post_share" post.id %}">
                                Click Here to share Post
                            </a>
                        </h4>
                    </div>

                    <div class="blog_d2 mt-4 shadow_box p-4 rounded_30">
                        {% with comments.count as total_comments %}
                            <h4 class="center_sm">
                               Comments{{ total_comments|pluralize }}  ( {{ total_comments }} )
                            </h4>
                        {% endwith %}
                        
                        <hr class="line mb-4">
                        {% for comment in comments %}
                        <div class="blog_d2i row">
                            <div class="col-md-10 col-sm-10">
                                <div class="blog_d2ir">
                                    <h5>{{ comment.name }}</h5>
                                    <h6 class="fw-normal mt-3 font_14"><a class="text-muted " href="#"><i class="fa fa-calendar col_blue me-1"></i>{{ comment.created}}</a> <a class="text-muted" href="#"><i class="fa fa-user col_blue me-1 ms-3"></i> {{ comment.name }}</a> <a class="text-muted " href="#"><i class="fa fa-comments col_blue me-1 ms-3"></i> {{ forloop.counter }} Comments</a></h6>
                                    <p class="mb-0 font_14 mt-3">
                                        {{ comment.body|linebreaks }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        {% empty %}
                        <p>There are no comments.</p>
                        {% endfor %}
                       
                    </div>
 {% comment %} {% include "blog/post/includes/comment_form.html" %} {% endcomment %}

                    </div>
                </div>  


                <div class="col-md-4">
                    <div class="blog_pg1r">
                        <div class="blog_pg1r1 bg_lighto pt-4 pb-4 rounded_30 mt-4">
                            <h5 class="px-4"> Trending topic <a class="col_blue float-end fs-6" href="#">View all</a></h5>
                            <hr>
                            <div class="blog_pg1r1i row px-4">
                                <div class="col-md-3 col-3">
                                    <div class="blog_pg1r1il">
                                        <a href="blog_detail.html"><img src="img/15.jpg" class="w-100 rounded_10" alt="img25"></a>
                                    </div>
                                </div>
                                <div class="col-md-9 col-9">
                                    <div class="blog_pg1r1ir">
                                        <h5 class="fs-6"><a href="#">Electronics</a></h5>
                                        <h6 class="mb-0 font_14">7 Articles</h6>
                                    </div>
                                </div>
                            </div>
                            <hr>
                            <div class="blog_pg1r1i row px-4">
                                <div class="col-md-3 col-3">
                                    <div class="blog_pg1r1il">
                                        <a href="blog_detail.html"><img src="img/16.jpg" class="w-100 rounded_10" alt="img25"></a>
                                    </div>
                                </div>
                                <div class="col-md-9 col-9">
                                    <div class="blog_pg1r1ir">
                                        <h5 class="fs-6"><a href="#">Industrial</a></h5>
                                        <h6 class="mb-0 font_14">9 Articles</h6>
                                    </div>
                                </div>
                            </div>
                            <hr>

                            <div class="blog_pg1r1i row px-4">
                                <div class="col-md-3 col-3">
                                    <div class="blog_pg1r1il">
                                        <a href="blog_detail.html"><img src="img/17.jpg" class="w-100 rounded_10" alt="img25"></a>
                                    </div>
                                </div>
                            <div class="col-md-9 col-9">
                                <div class="blog_pg1r1ir">
                                    <h5 class="fs-6"><a href="#">Tools</a></h5>
                                    <h6 class="mb-0 font_14">11 Articles</h6>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="blog_pg1r1i row px-4">
                            <div class="col-md-3 col-3">
                                <div class="blog_pg1r1il">
                                    <a href="blog_detail.html"><img src="img/18.jpg" class="w-100 rounded_10" alt="img25"></a>
                                </div>
                            </div>
                            <div class="col-md-9 col-9">
                                <div class="blog_pg1r1ir">
                                    <h5 class="fs-6"><a href="#">Health</a></h5>
                                    <h6 class="mb-0 font_14">16 Articles</h6>
                                </div>
                            </div>
                        </div>    
                    </div>

                    <div class="blog_pg1r1 bg_lighto pt-4 pb-4 rounded_30 mt-4">
                        <h5 class="px-4">  Popular Posts <a class="col_blue float-end fs-6" href="#">View all</a></h5>
                        <hr>
                        <div class="blog_1r1i row px-4">
                            <div class="col-md-9 col-sm-9">
                            <div class="blog_1r1ir">
                                <h6 class="font_13"><img width="40" height="40" src="img/10.jpg" class="rounded-circle me-2" alt="abc"> <span class="fw-bold">Augue Porta</span> - May 27, 2022</h6>
                                <h5 class="mb-0 fs-6"><a href="blog_detail.html">New tools for Black pregnant and postpartum mothers to save lives</a></h5>
                            </div>
                            </div>
                            <div class="col-md-3 col-sm-3">
                            <div class="blog_1r1il">
                                <a href="blog_detail.html"><img src="img/22.jpg" class="w-100 rounded_10" alt="img25"></a>
                            </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>        
{% endblock  %}

blog/templates/blog/post/latest_posts.html
{% comment %} <ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul> {% endcomment %}

{% for post in latest_posts %}
<div class="blog_1r1i row px-4">
    <div class="col-md-12 col-sm-12">
        <div class="blog_1r1ir">
            <h6 class="font_13">
                {% comment %} <img width="40" height="40" src="img/10.jpg" class="rounded-circle me-2" alt="abc"> {% endcomment %}
                 
            <h5 class="mb-0 fs-6"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h5>
            <span class="fw-bold">{{ post.author }}</span> - {{ post.publish }}</h6><hr/>
        </div>
    </div>
    {% comment %} <div class="col-md-3 col-sm-3">
        <div class="blog_1r1il">
            <a href="blog_detail.html"><img src="img/22.jpg" class="w-100 rounded_10" alt="img25"></a>
        </div>
    </div> {% endcomment %}
</div>
{% endfor %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load static %}

{% block title %}My Blog{% endblock  %}

{% block content %}
<!--  -->
<section id="center" class="center_blog pt-5 pb-5 px_4">
	<div class="container-fluid">
		<div class="blog_pg1 row">
			<div class="col-md-8">
				<div class="blog_pg1l">
					<div class="blog_pg1l1 row">
                        {% for post in posts %}
                        <div class="col-md-12">
                            <div class="blog_pg1l1l">
                                <h6>                     
                                    {% for tag in post.tags.all %}
                                        <a class="bg-primary d-inline-block rounded_30 p-2 px-4  font_13 text-white" href="{% url "blog:post_list_by_tag" tag.slug %}">
                                            {{ tag.name }}
                                        </a>
                                        {% if not forloop.last %}, {% endif %}
                                    {% endfor %} 
                                        <!--{{ post.tags.all|join:", "}} -->
                                </h6>
                                <h5 class="mt-3 fs-6">
                                    <a href="{{ post.get_absolute_url }}">
                                        {{ post.title }}
                                    </a>
                                </h5>
                                <p>
                                    {{ post.body|markdown|truncatewords_html:30 }}
                                </p>
                                <h6 class="font_13">
                                    <span class="fw-bold">{{ post.author }}</span> - {{ post.publish }}
                                </h6>
                                <div class="center_h2i1ili row mt-3">
                                    <div class="col-md-12 col-12">
                                        <div class="center_h2i1ilil">
                                            <ul class="mb-0 tags">
                                                <li class="d-inline-block"><a class="d-block" href="blog_detail.html"><i class="fa fa-heart me-1 align-middle"></i> 49</a></li>
                                                <li class="d-inline-block"><a class="d-block" href="blog_detail.html"><i class="fa fa-comment me-1 align-middle"></i> 118</a></li>
                                            </ul>
                                        </div>  
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% comment %} <div class="col-md-4">
                            <div class="blog_pg1l1r">
                            <a href="blog_detail.html"><img src="{% static 'blog/img/47.jpg' %}" alt="abc" class="w-100 rounded_30"></a>
                            </div>
                        </div>  {% endcomment %}
                    <hr>
                    {% endfor %}
                        {% include "pagination.html" with page=posts %}
                    </div>
			    </div>  
			</div>
           
            <div class="col-md-4">
                <div class="blog_pg1r1 bg_lighto pt-4 pb-4 rounded_30 mt-4">
                    <h5 class="px-4">  Latest Posts</h5>
                    <hr>
                    {% show_latest_posts 10 %}
                </div>

                <div class="blog_pg1r1 bg_lighto pt-4 pb-4 rounded_30 mt-4">
                    <h5 class="px-4"> Most commented posts</h5>
                    <hr>
                    {% get_most_commented_posts as most_commented_posts  %}
                    {% for post in most_commented_posts %}
                        <div class="blog_1r1i row px-4">
                            <div class="col-md-12 col-sm-12">
                                <div class="blog_1r1ir">
                                    <h6 class="font_13">
                                    <h5 class="mb-0 fs-6"><a href="{{ post.get_absolute_url }}">{{ post.title }}<hr></a></h5>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
		</div>
	</div>
</section> 

{% endblock  %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}


{% block title %}Search{% endblock %}

{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
            Found {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
        </h3>
    {% for post in results %}
        <h4>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h4>
    {{ post.body|markdown|truncatewords_html:12 }}
    {% empty %}
        <p>There are no results for your query.</p>
    {% endfor %}

    <p><a href="{% url "blog:post_search" %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}

{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock  %}

{% block content %}
{% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
        "{{post.title}}" was successfully sent to {{form.cleaned_data.to}}.
    </P>
    {% else %}
    <h1>Share "{{post.title}}" by e-mail</h1>
    <form method="post">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" value="Send e-mail">
    </form>
{% endif %}
{% endblock  %}