cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

hub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
     path('', views.index, name='index'), 
     path('list/', views.product_list, name='product_list'),
     path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
     path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse

# Your model code here


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])
    

class Product(models.Model):
    Category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created =models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm

def index(request):
    return render(request, 'shop/index.html')

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {'categoryy': category, 'categories': categories, 'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()

    return render(request, 'shop/product/detail.html', {'product': product, 'cart_product_form': cart_product_form})

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
 <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="author" content="">
    <meta name="keywords" content="">
    <meta name="description" content="">

    <title>{% block title %}PharosFleet Export - eCommerce Store{% endblock %} </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" media="all" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    
    
    <link rel="stylesheet" type="text/css" href="{% static 'shop/css/normalize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'shop/icomoon/icomoon.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'shop/css/vendor.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'shop/style.css' %}">

  <!-- script
    ================================================== -->
    <script src="{% static 'shop/js/modernizr.js' %}"></script>
    <script src="{% static 'shop/js/jquery-1.11.0.min.js' %}"></script>
    <script src="{% static 'shop/js/plugins.js' %}"></script>
    <script src="{% static 'shop/js/script.js' %}"></script>
 
 </head>
 <body>

    <!-- nav -->
    {% include 'shop/nav.html' %}
    <!--  -->

            <div id="content">
                    {% block content %}

                    {% endblock %}
            </div>


            <!-- footer -->
            {% include 'shop/footer.html' %}
            <!--  -->

 </body>
</html> 

shop/templates/shop/footer.html
{% load static %}

<footer id="footer">
    <div class="container">
      <div class="footer-menu-list">
        <div class="row d-flex flex-wrap justify-content-between">
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="footer-menu">
              <h5 class="widget-title">Links</h5>
              <ul class="menu-list list-unstyled">
                <li class="menu-item">
                  <a href="about.html">About us</a>
                </li>
                <li class="menu-item">
                  <a href="#">Conditions </a>
                </li>
                <li class="menu-item">
                  <a href="blog.html">Our Journals</a>
                </li>
                <li class="menu-item">
                  <a href="#">Careers</a>
                </li>
                <li class="menu-item">
                  <a href="#">Affiliate Programme</a>
                </li>
                <li class="menu-item">
                  <a href="#">Ultras Press</a>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="footer-menu">
              <h5 class="widget-title">Customer Service</h5>
              <ul class="menu-list list-unstyled">
                <li class="menu-item">
                  <a href="faqs.html">FAQ</a>
                </li>
                <li class="menu-item">
                  <a href="contact.html">Contact</a>
                </li>
                <li class="menu-item">
                  <a href="#">Privacy Policy</a>
                </li>
                <li class="menu-item">
                  <a href="#">Returns & Refunds</a>
                </li>
                <li class="menu-item">
                  <a href="#">Cookie Guidelines</a>
                </li>
                <li class="menu-item">
                  <a href="#">Delivery Information</a>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="footer-menu">
              <h5 class="widget-title">Contact Us</h5>
              <p>Do you have any questions or suggestions? <a href="#" class="email">ourservices@ultras.com</a>
              </p>
              <p>Do you need assistance? Give us a call. <br>
                <strong>+57 444 11 00 35</strong>
              </p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="footer-menu">
              <h5 class="widget-title">Forever 2018</h5>
              <p>Cras mattis sit ornare in metus eu amet adipiscing enim. Ullamcorper in orci, ultrices integer eget arcu. Consectetur leo dignissim lacus, lacus sagittis dictumst.</p>
              <div class="social-links">
                <ul class="d-flex list-unstyled">
                  <li>
                    <a href="#">
                      <i class="icon icon-facebook"></i>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="icon icon-twitter"></i>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="icon icon-youtube-play"></i>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="icon icon-behance-square"></i>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <hr>
  </footer>

  <div id="footer-bottom">
    <div class="container">
      <div class="d-flex align-items-center flex-wrap justify-content-between">
        <div class="copyright">
          <p> Pharosfleet Export Limited &copy 2019-2024
          </p>
        </div>
        <div class="payment-method">
          <p>Payment options :</p>
          <div class="card-wrap">
            <img src="{% static 'shop/images/visa-icon.jpg' %}" alt="visa">
            <img src="{% static 'shop/images/mastercard.png' %}" alt="mastercard">
            <img src="{% static 'shop/images/american-express.jpg' %}" alt="american-express">
          </div>
        </div>
      </div>
    </div>
  </div>

shop/templates/shop/nav.html
<div class="preloader-wrapper">
    <div class="preloader">
    </div>
  </div>

  {% include 'shop/searchpopup.html' %}

<!-- header -->
  <header id="header">
    <div id="header-wrap">
      {% include 'shop/nav1.html' %}
      <nav class="primary-nav padding-small">
        <div class="container">
          <div class="row d-flex align-items-center">
            <div class="col-lg-2 col-md-2">
              <div class="main-logo">
                <a href="index.html">
                  <h2>PharosFleet</h2>
                  <!-- <img src="images/main-logo.png" alt="logo"> -->
                </a>
              </div>
            </div>
            <div class="col-lg-10 col-md-10">
              <div class="navbar">

                <div id="main-nav" class="stellarnav d-flex justify-content-end right">
                  <ul class="menu-list">
                    <li><a href="{% url 'shop:index' %}" class="item-anchor active">Home</a></li>
                    <li><a  class="item-anchor" data-effect="About">Blog</a></li>
                    <li><a href="{% url 'shop:product_list' %}" class="item-anchor" data-effect="Shop">Shop</a></li>
                    <li><a  class="item-anchor" data-effect="About">Community</a></li>
                    <li><a class="item-anchor">E-Learning</a></li>
                    <li><a class="item-anchor">About Us</a></li>
                    <li><a href="" class="item-anchor" data-effect="Contact">Contact</a></li>
                  </ul>
                </div>

              </div>
            </div>
          </div>
        </div>
      </nav>
    </div>
  </header>

  <!-- <header id="header">
    <div id="header-wrap">
      {% include 'shop/nav1.html' %}
      <nav class="navbar navbar-expand-lg navbar-light bg-light" style="border: none;">
        <div class="container">
         
          <a class="navbar-brand" href="index.html">
            <h2>PharosFleet</h2>
          </a>
  
          
          <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
  
       
          <div class="collapse navbar-collapse position-fixed top-0 end-0 w-50 h-100 bg-dark p-3" id="navbarNav">
           
            <button type="button" class="btn-close text-white position-absolute top-0 end-0 m-3" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-label="Close"></button>
  
         
            <ul class="navbar-nav text-center w-100">
              <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'shop:index' %}">Home</a>
                <hr class="bg-white">
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="#">Blog</a>
                <hr class="bg-white">
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'shop:product_list' %}">Shop</a>
                <hr class="bg-white">
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="#">Community</a>
                <hr class="bg-white">
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="#">E-Learning</a>
                <hr class="bg-white">
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="#">About Us</a>
                <hr class="bg-white">
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="#">Contact</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </header>
   -->
  <!-- Custom CSS -->
  <style>
    /* Remove borders from toggler and navbar */
    /* .navbar-toggler {
      border: none;
    } */
  
    /* Toggler icon with dark lines */
    /* .navbar-toggler-icon {
      background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 30 30'%3E%3Cpath stroke='rgba%280, 0, 0, 1%29' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E");
    } */
  
    /* Remove border when toggler is clicked (active state) */
    /* .navbar-toggler:focus,
    .navbar-toggler:active {
      outline: none;
      box-shadow: none;
      border: none;
    }
   */
    /* Half-width menu settings */
    /* .navbar-collapse {
      width: 50%; 
      height: 100%;
      top: 0;
      right: 0;
      background-color: #343a40;
      z-index: 1050;
      padding-top: 3rem; Padding from top 
    }
   */
    /* Add the cancel button (X) */
    /* .btn-close {
      font-size: 1.5rem;
    }
   */
    /* Center menu items */
    /* .navbar-nav {
      display: flex;
      flex-direction: column;
      justify-content: center;
      height: 100%;
    }
  
    .navbar-nav .nav-item hr {
      margin: 1rem 0;
    } */
  </style>
  

shop/templates/shop/nav1.html
<nav class="secondary-nav border-bottom">
    <div class="container">
      <div class="row d-flex align-items-center">
        <div class="col-md-4 header-contact">
          <p>Let's talk! <strong>+234 444 11 00 35</strong>
          </p>
        </div>
        <div class="col-md-4 shipping-purchase text-center">
          <p>Free shipping on a purchase value of $200</p>
        </div>
        <div class="col-md-4 col-sm-12 user-items">
          <ul class="d-flex justify-content-end list-unstyled">
            <li>
              <a href="{% url 'account:login' %}">
                <i class="icon icon-user"></i>
              </a>
            </li>
            <li>
              
                {% with total_items=cart|length %}
                {% if total_items > 0 %}
                <a href="{% url 'cart:cart_detail' %}" class="position-relative">
                  <i class="icon icon-shopping-cart"> </i>
                    <span class="badge text-bg-success position-absolute top-0 start-100 translate-middle p-1 rounded-circle">
                      {{ total_items }}
                     </span>
                </a>
                {% elif not order %}
                <i class="icon icon-shopping-cart"></i>
                {% endif %}
                {% endwith %}
                
               
              
            </li>
            <li>
              <a href="wishlist.html">
                <i class="icon icon-heart"></i>
              </a>
            </li>
            <li class="user-items search-item pe-3">
              <a href="#" class="search-button">
                <i class="icon icon-search"></i>
              </a>
            </li>
           
          </ul>
        </div>
      </div>
    </div>
  </nav>

shop/templates/shop/product.html
{% load static %}

<section id="featured-products" class="product-store mt-5">
    <div class="container">
      <div class="section-header d-flex flex-wrap align-items-center justify-content-between">
        <h2 class="section-title">Products</h2>            
        <div class="btn-wrap">
          <a href="{% url 'shop:product_list' %}" class="d-flex align-items-center">View all products <i class="icon icon icon-arrow-io"></i></a>
        </div>            
      </div>
      
      <div class="swiper product-swiper overflow-hidden">
        <div class="swiper-wrapper">
          <div class="swiper-slide">
            <div class="product-item">
              <div class="image-holder">
                <img src="{% static 'shop/images/111.png'%}" alt="Books" class="product-image">
              </div>
              <div class="cart-concern">
                <div class="cart-button d-flex justify-content-between align-items-center">
                  <button type="button" class="btn-wrap cart-link d-flex align-items-center">
                    add to cart
                     <i class="icon icon-arrow-io"></i>
                  </button>
                  <button type="button" class="view-btn tooltip
                      d-flex">
                    <i class="icon icon-screen-full"></i>
                    <span class="tooltip-text">Quick view</span>
                  </button>
                  <button type="button" class="wishlist-btn">
                    <i class="icon icon-heart"></i>
                  </button>
                </div>
              </div>
              <div class="product-detail">
                <h3 class="product-title">
                  <a href="single-product.html">Premium Charcoal</a>
                </h3>
                <p>
                  Higher quality, more uniform charcoal often produced with improved methods.
                </p>
                <span class="item-price text-primary">₦40.00</span>
              </div>
            </div>
          </div>
          <div class="swiper-slide">
            <div class="product-item">
              <div class="image-holder">
                <img src="{% static 'shop/images/111.png'%}" alt="Books" class="product-image">
              </div>
              <div class="cart-concern">
                <div class="cart-button d-flex justify-content-between align-items-center">
                  <button type="button" class="btn-wrap cart-link d-flex align-items-center">add to cart <i class="icon icon-arrow-io"></i>
                  </button>
                  <button type="button" class="view-btn tooltip
                      d-flex">
                    <i class="icon icon-screen-full"></i>
                    <span class="tooltip-text">Quick view</span>
                  </button>
                  <button type="button" class="wishlist-btn">
                    <i class="icon icon-heart"></i>
                  </button>
                </div>
              </div>
              <div class="product-detail">
                <h3 class="product-title">
                  <a href="single-product.html">Briquette Charcoal</a>
                </h3>
                <p>
                  Compressed charcoal dust formed into briquettes.
                </p>
                <span class="item-price text-primary">₦38.00</span>
              </div>
            </div>
          </div>
          <div class="swiper-slide">
            <div class="product-item">
              <div class="image-holder">
                <img src="{% static 'shop/images/111.png'%}" alt="Books" class="product-image">
              </div>
              <div class="cart-concern">
                <div class="cart-button d-flex justify-content-between align-items-center">
                  <button type="button" class="btn-wrap cart-link d-flex align-items-center">add to cart <i class="icon icon-arrow-io"></i>
                  </button>
                  <button type="button" class="view-btn tooltip
                      d-flex">
                    <i class="icon icon-screen-full"></i>
                    <span class="tooltip-text">Quick view</span>
                  </button>
                  <button type="button" class="wishlist-btn">
                    <i class="icon icon-heart"></i>
                  </button>
                </div>
              </div>
              <div class="product-detail">
                <h3 class="product-title">
                  <a href="single-product.html">Activated Charcoal</a>
                </h3>
                <p>
                  Highly porous charcoal used for purification and health-related applications.
                </p>
                <span class="item-price text-primary">₦44.00</span>
              </div>
            </div>
          </div>
          <div class="swiper-slide">
            <div class="product-item">
              <div class="image-holder">
                <img src="{% static 'shop/images/111.png'%}" alt="Books" class="product-image">
              </div>
              <div class="cart-concern">
                <div class="cart-button d-flex justify-content-between align-items-center">
                  <button type="button" class="btn-wrap cart-link d-flex align-items-center">add to cart <i class="icon icon-arrow-io"></i>
                  </button>
                  <button type="button" class="view-btn tooltip
                      d-flex">
                    <i class="icon icon-screen-full"></i>
                    <span class="tooltip-text">Quick view</span>
                  </button>
                  <button type="button" class="wishlist-btn">
                    <i class="icon icon-heart"></i>
                  </button>
                </div>
              </div>
              <div class="product-detail">
                <h3 class="product-title">
                  <a href="single-product.html">Traditional Charcoal</a>
                </h3>
                <p>
                  Made from hardwood using traditional methods.
                </p>
                <span class="item-price text-primary">₦33.00</span>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="swiper-pagination"></div>
    </div>
  </section>

shop/templates/shop/searchpopup.html
<!-- Search popup -->
<div class="search-popup">
    <div class="search-popup-container">

      <form role="search" method="get" class="search-form" action="">
        <input type="search" id="search-form" class="search-field" placeholder="Type and press enter" value="" name="s" />
        <button type="submit" class="search-submit"><a href="#"><i class="icon icon-search"></i></a></button>
      </form>

      <h5 class="cat-list-title">Browse Categories</h5>
      
      <ul class="cat-list">
        <li class="cat-list-item">
          <a href="shop.html" title="Men Jackets">Men Jackets</a>
        </li>
        <li class="cat-list-item">
          <a href="shop.html" title="Fashion">Fashion</a>
        </li>
        <li class="cat-list-item">
          <a href="shop.html" title="Casual Wears">Casual Wears</a>
        </li>
        <li class="cat-list-item">
          <a href="shop.html" title="Women">Women</a>
        </li>
        <li class="cat-list-item">
          <a href="shop.html" title="Trending">Trending</a>
        </li>
        <li class="cat-list-item">
          <a href="shop.html" title="Hoodie">Hoodie</a>
        </li>
        <li class="cat-list-item">
          <a href="shop.html" title="Kids">Kids</a>
        </li>
      </ul>
    </div>
  </div>
<!-- sEARCH popup end  -->

shop/templates/shop/text.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Charcoal Platform</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>
    /* Custom styling for this section */
    .features-section {
      background-color: #f8f9fa;
      padding: 50px 0;
    }
    .features-section h2 {
      text-align: center;
      margin-bottom: 40px;
      color: #333;
    }
    .feature-icon {
      font-size: 40px;
      color: #a3d67a;
    }
    .feature-box {
      text-align: center;
      padding: 20px;
    }
    .feature-box h4 {
      margin-top: 15px;
      color: #333;
    }
    .feature-box p {
      color: #555;
    }
  </style>
</head>
<body>

<!-- Hero Section (above this section) -->
<section class="hero-section text-center p-5">
  <h1>Empowering Farmers, Promoting Sustainability, and Selling Quality Charcoal</h1>
  <p class="lead">Join a growing community of farmers and charcoal producers making a difference.</p>
  <a href="#" class="btn btn-lg btn-success mt-3">Join the Community</a>
</section>

<!-- Features Section (This Section After Hero) -->
<section class="features-section">
  <div class="container">
    <h2>Explore Our Features</h2>
    <div class="row">
      <!-- Home Feature -->
      <div class="col-md-4 feature-box">
        <div class="feature-icon">
          <i class="bi bi-house-door"></i>
        </div>
        <h4>Home</h4>
        <p>Your hub for the latest updates on charcoal production and sustainable practices.</p>
      </div>

      <!-- Blog Feature -->
      <div class="col-md-4 feature-box">
        <div class="feature-icon">
          <i class="bi bi-journal-text"></i>
        </div>
        <h4>Blog</h4>
        <p>Read articles, tips, and success stories about the charcoal industry and eco-friendly farming.</p>
      </div>

      <!-- Shop Feature -->
      <div class="col-md-4 feature-box">
        <div class="feature-icon">
          <i class="bi bi-cart4"></i>
        </div>
        <h4>Shop</h4>
        <p>Browse high-quality charcoal products produced by local farmers and entrepreneurs.</p>
      </div>

      <!-- Community Feature -->
      <div class="col-md-4 feature-box">
        <div class="feature-icon">
          <i class="bi bi-people"></i>
        </div>
        <h4>Community</h4>
        <p>Connect with fellow farmers, share insights, and collaborate on sustainable projects.</p>
      </div>

      <!-- E-Learning Feature -->
      <div class="col-md-4 feature-box">
        <div class="feature-icon">
          <i class="bi bi-mortarboard"></i>
        </div>
        <h4>E-Learning</h4>
        <p>Access courses on farming techniques, charcoal production, and entrepreneurship.</p>
      </div>
    </div>
  </div>
</section>

<!-- Bootstrap 5 JS and Popper.js -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>

<!-- Add Bootstrap Icons -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

</body>
</html>